export const MYINFO_ROUTE = '/myinfo'
export const SERVICES_ROUTE = '/services'
export const MAIN_ROUTE = '/'
export const CONTACTS_ROUTE = '/contacts'
export const CONSULTATION_ROUTE = '/consultation'